### ISSUE TITLE
Enable reification if and only if "reify" is listed as a dependency in package.json

### ISSUE THREAD

**Issue by benjamn** [benjamn/reify#13]
Dangerous situation we want to avoid:

1. code is able to use `import` and `export` statements because some unrelated code called `require("reify")`
2. unrelated code stops calling `require("reify")`
3. original code is now broken, though unchanged

This [step](https://github.com/benjamn/reify/blame/e30ced1453bb1ec8949e03b2fc9e0d7b98111e0e/README.md#L14) was added to `README.md` so that opting into reification would be explicit, but I think we can avoid that step by looking at the `dependencies`, `devDependencies`, and/or `peerDependencies` of the `package.json` file. If `"reify"` is listed there, then it should be enabled.

A separate `"reify": ...` property could still be useful for future configuration.

**Comment by ecwyne** [comment]
@benjamn 

It may be worth mentioning in the README that `reify` must be listed as a dependency in package.json. I was working on a tiny proof of concept and didn't add a package.json at all and was getting `Unexpected token 'import'`. I had used reify numerous times before but found myself on a wild goose chase trying to figure out why it wasn't working in my tiny example.

Absence of `package.json` currently fails silently because of https://github.com/benjamn/reify/blob/610484b3ea87c29a2e0dad12f7592ecb48c96d62/lib/node.js#L137-L138
